// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApiOffchainOrder
    {
        /// <summary>
        /// Initializes a new instance of the ApiOffchainOrder class.
        /// </summary>
        public ApiOffchainOrder()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApiOffchainOrder class.
        /// </summary>
        public ApiOffchainOrder(double volume, double price, double totalCost, double remainingVolume, double remainingOtherVolume, string id = default(string), string dateTime = default(string), string orderType = default(string), string asset = default(string), string assetPair = default(string))
        {
            Id = id;
            DateTime = dateTime;
            OrderType = orderType;
            Volume = volume;
            Price = price;
            Asset = asset;
            AssetPair = assetPair;
            TotalCost = totalCost;
            RemainingVolume = remainingVolume;
            RemainingOtherVolume = remainingOtherVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public string DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderType")]
        public string OrderType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalCost")]
        public double TotalCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemainingVolume")]
        public double RemainingVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemainingOtherVolume")]
        public double RemainingOtherVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
