// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClaimReferralLinkRequest
    {
        /// <summary>
        /// Initializes a new instance of the ClaimReferralLinkRequest class.
        /// </summary>
        public ClaimReferralLinkRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimReferralLinkRequest class.
        /// </summary>
        public ClaimReferralLinkRequest(bool isNewClient, string recipientClientId = default(string), string referalLinkUrl = default(string))
        {
            RecipientClientId = recipientClientId;
            ReferalLinkUrl = referalLinkUrl;
            IsNewClient = isNewClient;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RecipientClientId")]
        public string RecipientClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferalLinkUrl")]
        public string ReferalLinkUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsNewClient")]
        public bool IsNewClient { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
