// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClaimRefLinkResponse
    {
        /// <summary>
        /// Initializes a new instance of the ClaimRefLinkResponse class.
        /// </summary>
        public ClaimRefLinkResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimRefLinkResponse class.
        /// </summary>
        public ClaimRefLinkResponse(string transactionRewardRecipient = default(string), string transactionRewardSender = default(string), string senderOffchainTransferId = default(string))
        {
            TransactionRewardRecipient = transactionRewardRecipient;
            TransactionRewardSender = transactionRewardSender;
            SenderOffchainTransferId = senderOffchainTransferId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionRewardRecipient")]
        public string TransactionRewardRecipient { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionRewardSender")]
        public string TransactionRewardSender { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SenderOffchainTransferId")]
        public string SenderOffchainTransferId { get; set; }

    }
}
