// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetReferralLinksStatisticsBySenderIdResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetReferralLinksStatisticsBySenderIdResponse class.
        /// </summary>
        public GetReferralLinksStatisticsBySenderIdResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GetReferralLinksStatisticsBySenderIdResponse class.
        /// </summary>
        public GetReferralLinksStatisticsBySenderIdResponse(int numberOfInvitationLinksSent, int numberOfInvitationLinksAccepted, int numberOfGiftLinksSent, double amountOfGiftCoinsDistributed, int numberOfNewUsersBroughtIn)
        {
            NumberOfInvitationLinksSent = numberOfInvitationLinksSent;
            NumberOfInvitationLinksAccepted = numberOfInvitationLinksAccepted;
            NumberOfGiftLinksSent = numberOfGiftLinksSent;
            AmountOfGiftCoinsDistributed = amountOfGiftCoinsDistributed;
            NumberOfNewUsersBroughtIn = numberOfNewUsersBroughtIn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfInvitationLinksSent")]
        public int NumberOfInvitationLinksSent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfInvitationLinksAccepted")]
        public int NumberOfInvitationLinksAccepted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfGiftLinksSent")]
        public int NumberOfGiftLinksSent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AmountOfGiftCoinsDistributed")]
        public double AmountOfGiftCoinsDistributed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfNewUsersBroughtIn")]
        public int NumberOfNewUsersBroughtIn { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
