// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainSuccessTradeRespModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainSuccessTradeRespModel
        /// class.
        /// </summary>
        public OffchainSuccessTradeRespModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainSuccessTradeRespModel
        /// class.
        /// </summary>
        /// <param name="operationResult">Possible values include: 'Transfer',
        /// 'CreateChannel', 'ClientCommitment'</param>
        public OffchainSuccessTradeRespModel(OffchainOperationResult operationResult, string transferId = default(string), string transactionHex = default(string), ApiOffchainOrder order = default(ApiOffchainOrder))
        {
            TransferId = transferId;
            TransactionHex = transactionHex;
            OperationResult = operationResult;
            Order = order;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransferId")]
        public string TransferId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionHex")]
        public string TransactionHex { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Transfer', 'CreateChannel',
        /// 'ClientCommitment'
        /// </summary>
        [JsonProperty(PropertyName = "OperationResult")]
        public OffchainOperationResult OperationResult { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Order")]
        public ApiOffchainOrder Order { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Order != null)
            {
                Order.Validate();
            }
        }
    }
}
