// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainGroupLinkTransferToLykkeModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OffchainGroupLinkTransferToLykkeModel class.
        /// </summary>
        public OffchainGroupLinkTransferToLykkeModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OffchainGroupLinkTransferToLykkeModel class.
        /// </summary>
        public OffchainGroupLinkTransferToLykkeModel(string groupReferralLinkId = default(string), string prevTempPrivateKey = default(string))
        {
            GroupReferralLinkId = groupReferralLinkId;
            PrevTempPrivateKey = prevTempPrivateKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GroupReferralLinkId")]
        public string GroupReferralLinkId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrevTempPrivateKey")]
        public string PrevTempPrivateKey { get; set; }

    }
}
