// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainGetChannelKeyRequest
    {
        /// <summary>
        /// Initializes a new instance of the OffchainGetChannelKeyRequest
        /// class.
        /// </summary>
        public OffchainGetChannelKeyRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainGetChannelKeyRequest
        /// class.
        /// </summary>
        public OffchainGetChannelKeyRequest(string asset = default(string), string clientId = default(string))
        {
            Asset = asset;
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

    }
}
