// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Lykke.blue;
    using Lykke.blue.Service;
    using Lykke.blue.Service.ReferralLinks;
    using Lykke.blue.Service.ReferralLinks.Client;
    using Lykke.blue.Service.ReferralLinks.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RefLinkStatisticsRequest
    {
        /// <summary>
        /// Initializes a new instance of the RefLinkStatisticsRequest class.
        /// </summary>
        public RefLinkStatisticsRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RefLinkStatisticsRequest class.
        /// </summary>
        public RefLinkStatisticsRequest(string senderClientId = default(string))
        {
            SenderClientId = senderClientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SenderClientId")]
        public string SenderClientId { get; set; }

    }
}
