// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RefLinkStatisticsRequest
    {
        /// <summary>
        /// Initializes a new instance of the RefLinkStatisticsRequest class.
        /// </summary>
        public RefLinkStatisticsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RefLinkStatisticsRequest class.
        /// </summary>
        public RefLinkStatisticsRequest(string senderClientId = default(string))
        {
            SenderClientId = senderClientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SenderClientId")]
        public string SenderClientId { get; set; }

    }
}
