// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RequestRefLinkResponse
    {
        /// <summary>
        /// Initializes a new instance of the RequestRefLinkResponse class.
        /// </summary>
        public RequestRefLinkResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RequestRefLinkResponse class.
        /// </summary>
        public RequestRefLinkResponse(string refLinkId = default(string), string refLinkUrl = default(string))
        {
            RefLinkId = refLinkId;
            RefLinkUrl = refLinkUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RefLinkId")]
        public string RefLinkId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RefLinkUrl")]
        public string RefLinkUrl { get; set; }

    }
}
