// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Blue.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClaimGiftCoinsRequest
    {
        /// <summary>
        /// Initializes a new instance of the ClaimGiftCoinsRequest class.
        /// </summary>
        public ClaimGiftCoinsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimGiftCoinsRequest class.
        /// </summary>
        public ClaimGiftCoinsRequest(bool isNewUser, string id = default(string), string claimingUserId = default(string))
        {
            Id = id;
            IsNewUser = isNewUser;
            ClaimingUserId = claimingUserId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsNewUser")]
        public bool IsNewUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClaimingUserId")]
        public string ClaimingUserId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
