// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetReferralLinksStatisticsBySenderIdResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetReferralLinksStatisticsBySenderIdResponse class.
        /// </summary>
        public GetReferralLinksStatisticsBySenderIdResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GetReferralLinksStatisticsBySenderIdResponse class.
        /// </summary>
        public GetReferralLinksStatisticsBySenderIdResponse(int numberOfInvitationsSent, int numberOfInvitationAccepted, double amountOfCoinsDistributed, int numberOfNewUsersBroughtIn)
        {
            NumberOfInvitationsSent = numberOfInvitationsSent;
            NumberOfInvitationAccepted = numberOfInvitationAccepted;
            AmountOfCoinsDistributed = amountOfCoinsDistributed;
            NumberOfNewUsersBroughtIn = numberOfNewUsersBroughtIn;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfInvitationsSent")]
        public int NumberOfInvitationsSent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfInvitationAccepted")]
        public int NumberOfInvitationAccepted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AmountOfCoinsDistributed")]
        public double AmountOfCoinsDistributed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfNewUsersBroughtIn")]
        public int NumberOfNewUsersBroughtIn { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
