// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetReferralLinkResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetReferralLinkResponse class.
        /// </summary>
        public GetReferralLinkResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetReferralLinkResponse class.
        /// </summary>
        /// <param name="state">Possible values include: 'Initiated',
        /// 'Created', 'SentToRecipient', 'Claimed', 'Expired',
        /// 'CoinsReturnedToSender'</param>
        public GetReferralLinkResponse(System.DateTime expirationDate, ReferralLinkState state, double amount, string id = default(string), string url = default(string), string senderClientId = default(string), string asset = default(string), bool? isNewUser = default(bool?), string claimingClientId = default(string))
        {
            Id = id;
            Url = url;
            ExpirationDate = expirationDate;
            SenderClientId = senderClientId;
            Asset = asset;
            IsNewUser = isNewUser;
            State = state;
            Amount = amount;
            ClaimingClientId = claimingClientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpirationDate")]
        public System.DateTime ExpirationDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SenderClientId")]
        public string SenderClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsNewUser")]
        public bool? IsNewUser { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Initiated', 'Created',
        /// 'SentToRecipient', 'Claimed', 'Expired', 'CoinsReturnedToSender'
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public ReferralLinkState State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClaimingClientId")]
        public string ClaimingClientId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
