// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainChannelProcessModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainChannelProcessModel
        /// class.
        /// </summary>
        public OffchainChannelProcessModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainChannelProcessModel
        /// class.
        /// </summary>
        public OffchainChannelProcessModel(string transferId = default(string), string clientId = default(string), string signedChannelTransaction = default(string))
        {
            TransferId = transferId;
            ClientId = clientId;
            SignedChannelTransaction = signedChannelTransaction;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransferId")]
        public string TransferId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignedChannelTransaction")]
        public string SignedChannelTransaction { get; set; }

    }
}
