// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainFinalizeModel
    {
        /// <summary>
        /// Initializes a new instance of the OffchainFinalizeModel class.
        /// </summary>
        public OffchainFinalizeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainFinalizeModel class.
        /// </summary>
        public OffchainFinalizeModel(string transferId = default(string), string clientRevokePubKey = default(string), string clientRevokeEncryptedPrivateKey = default(string), string signedTransferTransaction = default(string), string clientId = default(string))
        {
            TransferId = transferId;
            ClientRevokePubKey = clientRevokePubKey;
            ClientRevokeEncryptedPrivateKey = clientRevokeEncryptedPrivateKey;
            SignedTransferTransaction = signedTransferTransaction;
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransferId")]
        public string TransferId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientRevokePubKey")]
        public string ClientRevokePubKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientRevokeEncryptedPrivateKey")]
        public string ClientRevokeEncryptedPrivateKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SignedTransferTransaction")]
        public string SignedTransferTransaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

    }
}
