// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ReferralLinks.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ReferralLinkState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReferralLinkState
    {
        [EnumMember(Value = "Initiated")]
        Initiated,
        [EnumMember(Value = "Created")]
        Created,
        [EnumMember(Value = "SentToRecipient")]
        SentToRecipient,
        [EnumMember(Value = "Claimed")]
        Claimed,
        [EnumMember(Value = "Expired")]
        Expired,
        [EnumMember(Value = "CoinsReturnedToSender")]
        CoinsReturnedToSender
    }
    internal static class ReferralLinkStateEnumExtension
    {
        internal static string ToSerializedValue(this ReferralLinkState? value)
        {
            return value == null ? null : ((ReferralLinkState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ReferralLinkState value)
        {
            switch( value )
            {
                case ReferralLinkState.Initiated:
                    return "Initiated";
                case ReferralLinkState.Created:
                    return "Created";
                case ReferralLinkState.SentToRecipient:
                    return "SentToRecipient";
                case ReferralLinkState.Claimed:
                    return "Claimed";
                case ReferralLinkState.Expired:
                    return "Expired";
                case ReferralLinkState.CoinsReturnedToSender:
                    return "CoinsReturnedToSender";
            }
            return null;
        }

        internal static ReferralLinkState? ParseReferralLinkState(this string value)
        {
            switch( value )
            {
                case "Initiated":
                    return ReferralLinkState.Initiated;
                case "Created":
                    return ReferralLinkState.Created;
                case "SentToRecipient":
                    return ReferralLinkState.SentToRecipient;
                case "Claimed":
                    return ReferralLinkState.Claimed;
                case "Expired":
                    return ReferralLinkState.Expired;
                case "CoinsReturnedToSender":
                    return ReferralLinkState.CoinsReturnedToSender;
            }
            return null;
        }
    }
}
